reaction: serial_dilution
deckSetup:
  reservoir:
    name:
      "4ti0131_12_reservoir_21000ul": "reservoir"
    slot:
      "2": "B1"
    wells:
      A1: "Fluorescin"
      A2: "PBS"
  plate:
    name:
      "costar3370flatbottomtransparent_96_wellplate_200ul": "plate"
    slot:
      "3": "A3"
  tipracks:
    slot:
      "1": "A1"
  trash:
    slot:
      "12": "C1"
    dropTipLocation:
      "12": "C1"
    setup_code: "trash = protocol.load_labware('opentrons_1_trash_1100ml_fixed', '{slot}')"

variable_ids:
  "p300_multi": "flex_8channel_1000"
  "plate_96": "serial_dilution_plate"
  "12_reservoir_21000ul": "flex_12_reservoir_15ml"
  "tiprack_300ul": "opentrons_flex_96_tiprack_1000ul"

labware:
  # OT-2 to Flex Labware Mapping
  # Reservoir
  "4ti0131_12_reservoir_21000ul": "nest_12_reservoir_15ml"
  # Tip racks
  "opentrons_96_tiprack_300ul": "opentrons_flex_96_tiprack_1000ul"
  # Well plates
  "costar3370flatbottomtransparent_96_wellplate_200ul": "nest_96_wellplate_100ul_pcr_full_skirt"

pipettes:
  # OT-2 to Flex Pipette Mapping
  "p300_multi_gen2": "flex_8channel_1000"

modules:
  # OT-2 to Flex Modules Mapping (if applicable)
  "heaterShakerModuleV1": "heaterShakerModuleV1"

commands:
  mix:
    from: "pipette.mix"
    to: "pipette.mix"
  aspirate:
    from: "pipette.aspirate"
    to: "pipette.aspirate"
  dispense:
    from: "pipette.dispense"
    to: "pipette.dispense"
  pick_up_tip:
    from: "pipette.pick_up_tip"
    to: "pipette.pick_up_tip"
  drop_tip:
    from: "pipette.drop_tip()"
    to: "pipette.drop_tip({trash_variable}['{dropTipLocation}'])"
  blow_out:
    from: "pipette.blow_out"
    to: "pipette.blow_out"

customFiles:
  - path: "/custom/serial_dilution/costar3370flatbottomtransparent_96_wellplate_200ul.json"
    variable: "serial_dilution_plate"
  - path: "/custom/serial_dilution/4ti0131_12_reservoir_21000ul.json"
    variable: "serial_dilution_reservoir"
